name: muslim
description: "Muslim APP"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  provider: ^6.1.2
  mvc_pattern: ^8.12.0
#  Set App Icon
#  Set App Splash
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: 'assets/images/logo.png'
  color : '1A1A1A'
  android: true
  ios: true

flutter_native_splash:
  image : 'assets/images/logo.png'
  color : 'FFFFFF'
  android: true
  ios: true





flutter:
  uses-material-design: true

  assets:
#    - i18n/
#    - i18n/ar.json
#    - i18n/en.json
    - assets/images/

