name: muslim
description: "Muslim APP"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  provider: ^6.1.2
  mvc_pattern: ^8.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true



